# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: v1beta1

import-mapping:
  "./core.yml": "github.com/meshery/schemas/models/core"
  "./common/core.yml": "github.com/meshery/schemas/models/core"
  "../../core.json": "github.com/meshery/schemas/models/core"
  "./common/parameters.yml": "github.com/meshery/schemas/models/core"

  # v1alpha1
  "../v1alpha1/capability.json": "github.com/meshery/schemas/models/v1alpha1/capability"
  "../v1alpha1/catalog_data.json": "github.com/meshery/schemas/models/v1alpha1/catalog_data"

  # v1alpha3
  "../v1alpha3/relationship.json": "github.com/meshery/schemas/models/v1alpha3/relationship"
  "../v1alpha3/selector.json": "github.com/meshery/schemas/models/v1alpha3/selector"

  # v1beta1
  "../v1beta1/model.json": "github.com/meshery/schemas/models/v1beta1/model"
  "../v1beta1/component.json": "github.com/meshery/schemas/models/v1beta1/component"
  "../v1beta1/connection.json": "github.com/meshery/schemas/models/v1beta1/connection"
  "../v1beta1/design.json": "github.com/meshery/schemas/models/v1beta1/design"
  # "../v1beta1/credential.json": "github.com/meshery/schemas/models/v1beta1/credential"
generate:
  models: true
output-options:
  # NOTE that this is only required for the `Unreferenced` type
  skip-prune: true
  exclude-tags:
    - "internal"
