openapi: 3.0.0
info:
  title: component
  version: 1.0.0
paths: {}
components:
  schemas:
    ComponentDefinition:
      $ref: "./component.json"

    Component:
      description: "data related to the third party capability that Component Defintion wraps , this is herematicaly sealed an"
      type: object
      properties:
        version:
          type: string
          description: "Version of the component produced by the registrant. Example: APIVersion of a Kubernetes Pod."
          x-order: 1
        kind:
          type: string
          description: "The unique identifier (name) assigned by the registrant to this component. Example: A Kubernetes Pod is of kind 'Pod'."
          x-order: 2
        schema:
          type: string
          description: "JSON schema of the object as defined by the registrant."
          x-order: 3
      required:
        - version
        - kind
        - schema
