openapi: 3.0.0
info:
  title: Academy API
  version: 1.0.0

paths:
  /api/academy/content:
    get:
      x-internal: ["cloud"]
      summary: Get academy content
      description: Returns a list of academy content with optional filtering.
      parameters:
        - name: contentType
          in: query
          description: Filter content by content types
          required: false
          schema:
            type: array
            items:
              type: string
            style: form
            explode: true
        - name: visibility
          in: query
          description: Filter content by visibility (public/private)
          required: false
          schema:
            type: array
            items:
              type: string
            style: form
            explode: true

        - name: level
          in: query
          description: Filter content by difficulty level
          required: false
          schema:
            type: array
            items:
              type: string
            style: form
            explode: true

        - name: orgId
          in: query
          description: Filter content by organization IDs
          required: false
          schema:
            type: array
            items:
              type: string
            style: form
            explode: true

        - name: category
          in: query
          description: Filter content by categories
          required: false
          schema:
            type: array
            items:
              type: string
            style: form
            explode: true


        - name: status
          in: query
          description: Filter by registration status
          required: false
          schema:
            type: array
            items:
              type: string
            style: form
            explode: true

        - name: search
          in: query
          description: Search content by title
          required: false
          schema:
            type: string

    responses:
      '200':
        description: A list of content with total count
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcademyCirriculaListResponse'
      '400':
        description: Invalid request parameters
      '500':
        description: Server error

  /api/academy/{type}/{orgId}/{slug}:
    get:
      x-internal:
        - cloud
      summary: Get a single learning path
      description: Returns a learning path identified by type, orgId, and slug.
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: orgId
          in: path
          required: true
          schema:
            type: string
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single academy content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcademyCirricula'
        '400':
          description: Invalid request parameters
        '500':
          description: Server error


  /api/academy/register:
    post:
      x-internal: ["cloud"]
      tags:
        - Academy
      summary: Register a user to academy content
      operationId: registerToAcademyContent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterToAcademyContentRequest'

      responses:
        '200':
          description: registered content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcademyRegistration'
        '400':
          description: Invalid request parameters
        '500':
          description: Server error



  /api/academy/registrations/{contentId}:
    get:

      tags:
        - Academy

      x-internal: ["cloud"]
      summary: Get registration information for academy content
      description: Returns registration data for a specific content item, optionally filtered by status.
      parameters:
        - name: contentId
          in: path
          required: true
          description: The ID of the content to retrieve registration data for
          schema:
            type: string

        - name: status
          in: query
          required: false
          description: Filter registrations by status (e.g., registered, completed)
          schema:
            type: string

      responses:
        '200':
          description: Registration data for the specified content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcademyRegistration'
        '400':
          description: Invalid request parameters
        '404':
          description: Content not found
        '500':
          description: Server error

  /api/academy/registrations/{registrationId}/progress-tracker/update-current-item:
    post:
      tags:
        - Academy
      x-internal: ["cloud"]
      operationId: updateCurrentItemInProgressTracker
      summary: Update the current item in the progress tracker
      parameters:
        - name: registrationId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCurrentItemRequest'
      responses:
        '200':
          description: Successfully updated the progress tracker
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  progress_tracker:
                    $ref: '#/components/schemas/CirriculaProgressTracker'
                  registration_id:
                    type: string
                  content_type:
                    $ref: '#/components/schemas/ContentType'
                  item_data:
                    $ref: '#/components/schemas/CirriculaCurrentItemData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:


    RegisterToAcademyContentRequest:
      type: object
      required:
        - content_id
        - user_id
      properties:
        content_id:
          type: string
          description: ID of the academy content to register for
        content_type:
          $ref: "#/components/schemas/ContentType"

    ContentType:
      type: string
      enum:
        - learning-path
        - challenge
        - exam

    Visibility:
      type: string
      enum:
        - public
        - private
    Level :
      type: string
      enum:
        - beginner
        - intermediate
        - advanced

    Status:
      type: string
      enum:
        - ready
        - archived
        - not_ready

    AcademyCirricula:
      type: object
      properties:
        id :
          type: string
          description: Id of the cirricula
          example: 923458-3490394-934893
          x-go-name: ID
          x-oapi-codegen-extra-tags:
            db: "id"
            json: "id"
            yaml: "id"

        type :
           $ref: "#/components/schemas/ContentType"
           x-go-type: "ContentType"
           x-oapi-codegen-extra-tags:
             db: "type"
        orgId:
          type: string
          description: Organization ID that owns this learning path
          example: layer5
          x-oapi-codegen-extra-tags:
            db: "org_id"
            json: "org_id"
            yaml: "org_id"
        visibility:
          $ref: "#/components/schemas/Visibility"
          description: Visibility of the cirricula
          x-go-type: "Visibility"
          x-oapi-codegen-extra-tags:
            db: "visibility"
            json: "visibility"
            yaml: "visibility"
        status:
          $ref: "#/components/schemas/Status"
          example: ready
          description: Status of the cirricula
          x-go-type: "Status"
          x-oapi-codegen-extra-tags:
            db: "status"
            json: "status"
            yaml: "status"

        slug :
          type: string
          description: slug of the cirricula
          example: intro-kubernetes-course

        level:
          $ref: "#/components/schemas/Level"
          description: Level of the cirricula
          x-go-type: "Level"
          x-oapi-codegen-extra-tags:
            db: "level"
            json: "level"
            yaml: "level"



        createdAt:
          description: When the cirricula item was created
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/Time"
          x-oapi-codegen-extra-tags:
            db: "created_at"
            json: "created_at"
            yaml: "created_at"


        updatedAt:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/Time"
          description: When the cirricula was last updated
          x-go-type: "core.Time"
          x-oapi-codegen-extra-tags:
            db: "updated_at"
            json: "updated_at"
            yaml: "updated_at"
        deletedAt:
          x-go-type : "core.NullTime"
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/deleted_at"
          x-oapi-codegen-extra-tags:
            db: "deleted_at"
            json: "deleted_at"
            yaml: "deleted_at"
        metadata:
          type: object
          description: Additional metadata about the cirricula
          additionalProperties: true
          x-go-type: "core.Map"
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            db: "metadata"
            json: "metadata"
            yaml: "metadata"
          oneOf:
            - $ref: "#/components/schemas/LearningPathMetadata"
            - $ref: "#/components/schemas/ChallengeMetadata"

      required:
        - id
        - type
        - orgId
        - visibility
        - status
        - slug
        - createdAt
        - updatedAt
        - deletedAt
        - metadata
        - level

    AcademyCirriculaListResponse:
      type: object
      properties:
        total:
          type: integer
          description: Total number of cirricula
          example: 7
        data:
          type: array
          items:
            x-go-type: "AcademyCirricula"
            $ref: '#/components/schemas/AcademyCirricula'
      required:
        - total
        - data

    ChallengeMetadata:
      $ref: "#/components/schemas/LearningPathMetadata"

    LearningPathMetadata:
      type: object
      properties:
        title:
          type: string
          description: Title of the learning path
          example: Mastering Kubernetes for Engineers
        description:
          type: string
          description: Description of the learning path
          example: Learn how to configure your Kubernetes clusters and manage the lifecycle of your workloads
        banner:
          type: string
          format: uri
          nullable: true
          description: Optional banner image
          example: null
        permalink:
          type: string
          format: uri
          description: Canonical URL for the learning path
          example: http://localhost:9876/academy/learning-paths/layer5/mastering-kubernetes-for-engineers/
        courses:
          type: array
          description: List of courses in this learning path
          items:
            x-go-type: "Course"
            $ref: '#/components/schemas/Course'


      required:
        - title
        - description
        - permalink

    AcademyRegistration:
      type: object
      required:
        - ID
        - org_id
        - user_id
        - status
        - created_at
        - updated_at
        - content_id
        - metadata
      properties:
        ID:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/uuid"
          x-oapi-codegen-extra-tags:
            db: "id"
            json: "id"
            yaml: "id"

        org_id:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/uuid"
          description: ID of the organization

          x-oapi-codegen-extra-tags:
            db: "org_id"

        content_id:
          type: string
          description: ID of the course content

          x-oapi-codegen-extra-tags:
            db: "content_id"

        user_id:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/uuid"
          description: ID of the user (foreign key to User)

          x-oapi-codegen-extra-tags:
            db: "user_id"

        status:
          type: string
          enum:
            - registered
            - in_progress
            - completed
            - failed
            - withdrawn
          description: Status of the user's course registration
          x-oapi-codegen-extra-tags:
            db: "status"

        updated_at:
          description: When the registration was updated
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/Time"
          x-oapi-codegen-extra-tags:
            db: "updated_at"


        created_at:
          description: When the registration was created
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/Time"
          x-oapi-codegen-extra-tags:
            db: "created_at"

        deleted_at:
          x-go-type : "core.NullTime"
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/deleted_at"
          x-oapi-codegen-extra-tags:
            db: "deleted_at"


        metadata:
          type: object
          description: Additional metadata about the registration
          additionalProperties: true
          x-go-type: "core.Map"
          x-go-type-skip-optional-pointer: true

          x-oapi-codegen-extra-tags:
            db: "metadata"


    Course:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the course
          example: 1234567890abcdef
          x-go-name: ID
          x-oapi-codegen-extra-tags:
            db: "id"
            json: "id"
            yaml: "id"
        title:
          type: string
          description: Title of the course
          example: Kubernetes Basics
        permalink:
          type: string
          format: uri
          description: URL to the course content
          example: http://localhost:9876/academy/learning-paths/layer5/intro-kubernetes-course/kubernetes/
        description:
          type: string
          description: Course description
          example: Learn the basics of Kubernetes
        weight:
          type: number
          description: Order of the course in the list
          example: eg 1 , 2
        banner:
          type: string
          format: uri
          nullable: true
          description: Optional banner image
          example: null
      required:
        - title
        - description
        - id
        - permalink


    AcademyRegistrationsListResponse:
      type: object
      properties:
        total:
          type: integer
          description: Total number of learning paths
          example: 7
        data:
          type: array
          items:
            x-go-type: "AcademyRegistration"
            $ref: '#/components/schemas/AcademyRegistration'
      required:
        - total
        - data

    CirriculaGrade:
      type: object
      required:
        - module_id
        - grade
        - attempts
        - passed
      properties:
        module_id:
          type: string
        grade:
          type: string
        attempts:
          type: integer
        passed:
          type: boolean

    CirriculaCurrentItemData:
      type: object
      required:
        - id
        - last_opened
        - content_type
      properties:
        id:
          type: string
        last_opened:
          type: string
          format: date-time
        content_type:
          $ref: '#/components/schemas/ContentType'
          x-go-type: "ContentType"

    CirriculaProgressTracker:
      type: object
      required:
        - current_item
        - grades
        - time_spent
        - completed
      properties:
        current_item:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CirriculaCurrentItemData'
            x-go-type: "CirriculaCurrentItemData"
        grades:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CirriculaGrade'
            x-go-type: "CirriculaGrade"
        time_spent:
          type: integer
          description: Total time spent in seconds
        completed:
          type: string
          format: date-time
          x-go-type: "core.NullTime"

    UpdateCurrentItemRequest:
      type: object
      properties:
        content_type:
          $ref: '#/components/schemas/ContentType'
          x-go-type: "ContentType"
        item_data:
          $ref: '#/components/schemas/CirriculaCurrentItemData'
          x-go-type: "CirriculaCurrentItemData"
      required:
        - content_type
        - item_data

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        details:
          type: string